package com.example.mosnterguideapi.model.Enum;

public enum MonsterTypeEnum {
    ABOMINATION, CORRUPTED, SEA_CREATURE, SPIRIT, UNDEAD, DEMONIC, ANGELIC, ABYSSAL, MUTATED, OCCULT_ENTITY, ANCIENT_BEING, CURSED, BLOODBORNE, SHADOW, DREAM_ENTITY
}
